# Site settings
title: Ricardo Canales
description: >
  Ricardo Canales's blog page. Might serve for multiple purposes. Static webpage. Project experiences and more..

# baseurl: "/blog/" # the subpath of your site, e.g. /blog/
# url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Ricardo Canales
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: canalesb93
  linkedin: canalesb93
  mail: canalesb93@gmail.com
  # twitter: electrik_frog
  disqus: canalesb93

google_analytics: 'UA-68453825-1'

# Build settings
markdown: kramdown